### ISSUE TITLE
Clip example

### ISSUE THREAD

**Issue by etiquetasio** [robvanderleek/capture-website-api#399]
Hello again, 

Can you provide a example with 'clip' option ? ( to get only a specific window size of a page ) ?

thank u !

**Comment by robvanderleek** [comment]
Hi @etiquetasio 

This project is a wrapper around https://github.com/sindresorhus/capture-website (the `clip` option is [documented here](https://github.com/sindresorhus/capture-website#clip)).

If you want to pass the `clip` option you need to [pass it as a query parameter](https://github.com/robvanderleek/capture-website-api#capturing-options).
Since the value of the `clip` option is an object it's best to URL encode it first:

```javascript
console.log(encodeURIComponent(JSON.stringify({
    x: 0,
    y: 0,
    width: 400,
    height: 400
})));
```

The above returns `%7B%22x%22%3A0%2C%22y%22%3A0%2C%22width%22%3A400%2C%22height%22%3A400%7D`.
You can use that value in the URL like this:

```shell
curl 'localhost:8080/capture?url=http://amazon.com&width=650&height=350&clip=%%7B%22x%22%3A0%2C%22y%22%3A0%2C%22width%22%3A400%2C%22height%22%3A400%7D' -o screenshot.png
```

HTH, Rob
